export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export const SET_LOADING_PRODUCTS = "SET_LOADING_PRODUCTS";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const SET_LOADING_CATEGORIES_UI = "SET_LOADING_CATEGORIES";

export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
