export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";
export const SET_LOADING_PRODUCTS = "SET_LOADING_PRODUCTS";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const SET_LOADING_CATEGORIES_UI = "SET_LOADING_CATEGORIES";

export const GET_USER_CART = "GET_USER_CART";
export const SET_LOADING_USER_CART = "SET_LOADING_USER_CART";
export const UNSET_LOADING_USER_CART = "UNSET_LOADING_USER_CART";
